name: textvis
dependencies:
- appnope=0.1.0=py27_0
- backports_abc=0.4=py27_0
- boto=2.40.0=py27_0
- bz2file=0.98=py27_0
- cloudpickle=0.1.1=py27_0
- cycler=0.10.0=py27_0
- cymem=1.30=py27_0
- decorator=4.0.9=py27_0
- freetype=2.5.5=0
- gensim=0.12.4=np110py27_0
- ipykernel=4.3.1=py27_0
- ipython=4.1.2=py27_0
- ipython_genutils=0.1.0=py27_0
- ipywidgets=4.1.1=py27_0
- jinja2=2.8=py27_0
- jsonschema=2.4.0=py27_0
- jupyter=1.0.0=py27_2
- jupyter_client=4.1.1=py27_0
- jupyter_console=4.1.0=py27_0
- jupyter_core=4.0.6=py27_0
- libpng=1.6.17=0
- markupsafe=0.23=py27_0
- matplotlib=1.5.1=np110py27_0
- mistune=0.7.1=py27_0
- mkl=11.3.3=0
- murmurhash=0.24=py27_0
- nbconvert=4.1.0=py27_0
- nbformat=4.0.1=py27_0
- nltk=3.1=py27_0
- notebook=4.1.0=py27_0
- numpy=1.10.4=py27_2
- openssl=1.0.2g=0
- pandas=0.18.1=np110py27_0
- path.py=8.1.2=py27_1
- pexpect=3.3=py27_0
- pickleshare=0.5=py27_0
- pip=8.0.3=py27_0
- plac=0.9.1=py27_0
- preshed=0.44=py27_0
- ptyprocess=0.5=py27_0
- pygments=2.1.1=py27_0
- pyparsing=2.0.3=py27_0
- pyqt=4.11.4=py27_1
- python=2.7.11=0
- python-dateutil=2.4.2=py27_0
- python.app=1.2=py27_4
- pytz=2015.7=py27_0
- pyyaml=3.11=py27_1
- pyzmq=15.2.0=py27_0
- qt=4.8.7=1
- qtconsole=4.1.1=py27_0
- readline=6.2=2
- requests=2.10.0=py27_0
- scikit-learn=0.17.1=np110py27_1
- scipy=0.17.0=np110py27_4
- setuptools=20.1.1=py27_0
- simplegeneric=0.8.1=py27_0
- singledispatch=3.4.0.3=py27_0
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- smart_open=1.3.3=py27_0
- sqlite=3.9.2=0
- ssl_match_hostname=3.4.0.2=py27_0
- terminado=0.5=py27_1
- text-unidecode=1.0=py27_0
- thinc=4.0.0=py27_0
- tk=8.5.18=0
- tornado=4.3=py27_0
- traitlets=4.1.0=py27_0
- ujson=1.33=py27_0
- wheel=0.29.0=py27_0
- yaml=0.1.6=0
- zeromq=4.1.3=0
- zlib=1.2.8=0
- pip:
  - backports-abc==0.4
  - backports.ssl-match-hostname==3.4.0.2
  - click==6.6
  - coverage==4.0.3
  - dateparser==0.3.1
  - future==0.15.2
  - html5lib==0.9999999
  - htrc-feature-reader==1.42
  - isodate==0.5.4
  - jdatetime==1.7.1
  - keepalive==0.5
  - linecache2==1.0.0
  - pysolr==3.4.0
  - rdflib==4.2.1
  - smart-open==1.3.3
  - sparqlwrapper==1.7.6
  - textkit==0.2.1
  - traceback2==1.4.0
  - unittest2==1.1.0

